#!/bin/bash

echo "🚀 Dytallix Deployment Helper"
echo "========================================="
echo ""
echo "This script will help you connect to your Hetzner server and deploy the system."
echo ""
echo "Step 1: Connecting to server..."
echo "Run this command to connect:"
echo ""
echo "ssh root@178.156.187.81"
echo ""
echo "Step 2: Once connected, run these commands on the server:"
echo ""
echo "cd ~/dytallix"
echo "docker-compose -f docker-compose/docker-compose-faucet.yml down"
echo "docker-compose -f docker-compose/docker-compose-faucet.yml up -d"
echo "docker ps"
echo ""
echo "Step 3: Test the deployment:"
echo ""
echo "curl -s http://localhost:26657/status | jq ."
echo "curl -s http://localhost:3001/api/health"
echo "curl -s -I http://localhost:8080"
echo ""
echo "Step 4: Open external ports (if needed):"
echo ""
echo "ufw allow 26657/tcp comment 'Tendermint RPC'"
echo "ufw allow 26656/tcp comment 'Tendermint P2P'"
echo "ufw allow 8080/tcp comment 'Faucet Frontend'"
echo "ufw allow 3001/tcp comment 'Faucet API'"
echo "ufw reload"
echo ""
echo "========================================="
echo "Ready to connect? Press Enter to open SSH connection..."
read

# Open SSH connection
ssh root@178.156.187.81
