// Package developmentintent records one typed root intent in a caller's atomic
// store. It has no production entry point and performs no upgrade or halt.
package developmentintent

import (
	"bytes"
	"crypto/sha512"
	"encoding/hex"
	"encoding/json"
	"errors"

	root "github.com/dytallix/root-authorization"
)

const (
	Version uint16 = 1
	Mode           = "development-only"
	// HardArtifactLimit is an implementation cap, not an approved mainnet limit.
	HardArtifactLimit = 8192
	hardStateLimit    = 16384
)

var (
	ErrSchema  = errors.New("invalid or noncanonical development intent")
	ErrPolicy  = errors.New("development intent does not match explicit trusted policy")
	ErrState   = errors.New("development intent state does not match trusted state")
	ErrPending = errors.New("a development intent is already pending")
)

// Artifact has exactly one action body. Strings that name digests or intent IDs
// contain 128 lowercase hexadecimal characters and cannot represent zero.
// Canonical bytes are JSON generated by json.Marshal of this exact struct:
// field order is fixed, all fields are present, and absent bodies are null.
// Decoding rejects alternate encodings, duplicate keys and additional fields.
// This is a development wire format. It is not a production action schema.
type Artifact struct {
	Version          uint16      `json:"version"`
	Mode             string      `json:"mode"`
	ChainID          string      `json:"chain_id"`
	Action           root.Action `json:"action"`
	IntentID         string      `json:"intent_id"`
	CurrentRelease   string      `json:"current_release_sha512"`
	ApprovalRecord   string      `json:"approval_record_sha512"`
	ActivationHeight uint64      `json:"activation_height"`
	Upgrade          *Upgrade    `json:"upgrade"`
	Halt             *Halt       `json:"halt"`
}

type Upgrade struct {
	NextRelease  string `json:"next_release_sha512"`
	SourceSchema uint32 `json:"source_schema"`
	TargetSchema uint32 `json:"target_schema"`
	Migration    string `json:"migration_sha512"`
	// LastRollbackHeight is an explicit reviewed boundary. Recording it does
	// not implement rollback or assert that a migration is reversible.
	LastRollbackHeight uint64 `json:"last_rollback_height"`
}

type Halt struct {
	// Scope has only one development value, "consensus". No resume, spending,
	// key replacement, validator changes or arbitrary state effects exist.
	Scope        string `json:"scope"`
	AnchorHeight uint64 `json:"anchor_height"`
	Anchor       string `json:"anchor_sha512"`
	ReviewHeight uint64 `json:"review_height"`
	Incident     string `json:"incident_sha512"`
}

// TrustedPolicy must come from an independent trusted caller. No field is
// derived from a submitted envelope or artifact. Heights and byte limits have
// no defaults. ApprovalRecord binds a reference; it does not verify approvals,
// quorum, custody, delay policy, or reviewer independence.
type TrustedPolicy struct {
	Mode                    string
	ChainID                 string
	Action                  root.Action
	FinalizedHeight         uint64
	CurrentRelease          string
	StateSchema             uint32
	CurrentAnchor           string
	ApprovedArtifactDigest  [sha512.Size]byte
	ApprovalRecord          string
	NotBeforeHeight         uint64
	NotAfterHeight          uint64
	MinimumActivationHeight uint64
	MaximumActivationHeight uint64
	MaxArtifactBytes        uint32
}

// State is the entire application document for this development component.
// Active release/schema remain unchanged when an intent is recorded. Pending
// cannot be replaced, cleared, activated or expired through this package.
// Do not use a separate FileStore as a replay ledger for a chain transaction.
type State struct {
	Version        uint16   `json:"version"`
	Mode           string   `json:"mode"`
	ChainID        string   `json:"chain_id"`
	CurrentRelease string   `json:"current_release_sha512"`
	StateSchema    uint32   `json:"state_schema"`
	CurrentAnchor  string   `json:"finalized_anchor_sha512"`
	Pending        *Receipt `json:"pending"`
}

type Receipt struct {
	Sequence       uint64   `json:"sequence"`
	AdmittedHeight uint64   `json:"admitted_height"`
	ArtifactDigest string   `json:"artifact_sha512"`
	Intent         Artifact `json:"intent"`
}

func digest(value string) bool {
	if len(value) != sha512.Size*2 {
		return false
	}
	nonzero := false
	for _, c := range []byte(value) {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return false
		}
		nonzero = nonzero || c != '0'
	}
	return nonzero
}

func chainID(value string) bool {
	if len(value) == 0 || len(value) > root.MaxChainIDSize {
		return false
	}
	for _, c := range []byte(value) {
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.') {
			return false
		}
	}
	return true
}

func canonical(data []byte, limit uint32, value any) error {
	if len(data) == 0 || uint64(len(data)) > uint64(limit) {
		return ErrSchema
	}
	d := json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if d.Decode(value) != nil {
		return ErrSchema
	}
	encoded, err := json.Marshal(value)
	if err != nil || !bytes.Equal(encoded, data) {
		return ErrSchema
	}
	return nil
}

func validatePolicy(p TrustedPolicy) error {
	if p.Mode != Mode || !chainID(p.ChainID) ||
		(p.Action != root.Upgrade && p.Action != root.Emergency) ||
		!digest(p.CurrentRelease) || p.StateSchema == 0 || !digest(p.ApprovalRecord) ||
		p.ApprovedArtifactDigest == [sha512.Size]byte{} ||
		p.MaxArtifactBytes == 0 || p.MaxArtifactBytes > HardArtifactLimit ||
		p.NotBeforeHeight > p.FinalizedHeight || p.NotAfterHeight < p.FinalizedHeight ||
		p.MinimumActivationHeight < p.FinalizedHeight ||
		p.MaximumActivationHeight < p.MinimumActivationHeight {
		return ErrPolicy
	}
	if !digest(p.CurrentAnchor) {
		return ErrPolicy
	}
	return nil
}

func validateArtifact(data []byte, p TrustedPolicy) (Artifact, error) {
	var a Artifact
	if err := validatePolicy(p); err != nil {
		return a, err
	}
	if err := canonical(data, p.MaxArtifactBytes, &a); err != nil {
		return a, err
	}
	if a.Version != Version || a.Mode != Mode || !chainID(a.ChainID) ||
		!digest(a.IntentID) || !digest(a.CurrentRelease) || !digest(a.ApprovalRecord) {
		return a, ErrSchema
	}
	if a.ChainID != p.ChainID || a.Action != p.Action || a.CurrentRelease != p.CurrentRelease ||
		a.ApprovalRecord != p.ApprovalRecord || root.DigestArtifact(data) != p.ApprovedArtifactDigest ||
		a.ActivationHeight < p.MinimumActivationHeight || a.ActivationHeight > p.MaximumActivationHeight {
		return a, ErrPolicy
	}
	switch a.Action {
	case root.Upgrade:
		u := a.Upgrade
		if u == nil || a.Halt != nil || !digest(u.NextRelease) || u.NextRelease == a.CurrentRelease ||
			u.SourceSchema != p.StateSchema || u.TargetSchema == 0 || !digest(u.Migration) ||
			u.LastRollbackHeight < a.ActivationHeight {
			return a, ErrSchema
		}
	case root.Emergency:
		h := a.Halt
		if h == nil || a.Upgrade != nil || h.Scope != "consensus" ||
			h.AnchorHeight != p.FinalizedHeight || h.Anchor != p.CurrentAnchor ||
			!digest(h.Incident) || h.ReviewHeight < a.ActivationHeight {
			return a, ErrSchema
		}
	default:
		return a, ErrSchema
	}
	return a, nil
}

// InitialState constructs an empty development intent document from explicit
// trusted values. It does not initialize root keys or consumed sequences.
func InitialState(chain, release, anchor string, schema uint32) ([]byte, error) {
	if !chainID(chain) || !digest(release) || !digest(anchor) || schema == 0 {
		return nil, ErrState
	}
	return json.Marshal(State{Version: Version, Mode: Mode, ChainID: chain, CurrentRelease: release, CurrentAnchor: anchor, StateSchema: schema})
}

// Record validates a typed artifact, verifies the existing root signature, and
// records the pending intent and root sequence in one ExecutionStore.Update.
// It changes no active release, consensus rule, balance, key or process.
// Durability depends on the supplied store contract. No production database
// adapter or chain consumer is supplied. The development marker is mandatory;
// setting it does not make an unqualified store safe for production use.
func Record(store root.ExecutionStore, p TrustedPolicy, e root.Envelope, signature, artifact []byte) error {
	if err := validatePolicy(p); err != nil {
		return err
	}
	if len(artifact) == 0 || uint64(len(artifact)) > uint64(p.MaxArtifactBytes) {
		return ErrSchema
	}
	artifact = bytes.Clone(artifact)
	if _, err := validateArtifact(artifact, p); err != nil {
		return err
	}
	if len(signature) != root.SignatureSize {
		return root.ErrSignature
	}
	if e.NotBeforeHeight != p.NotBeforeHeight || e.NotAfterHeight != p.NotAfterHeight {
		return ErrPolicy
	}
	intent := root.ExecutionIntent{ChainID: p.ChainID, Action: p.Action, ArtifactDigest: p.ApprovedArtifactDigest, FinalizedHeight: p.FinalizedHeight}
	return root.Execute(store, intent, e, signature, artifact, func(current, exactArtifact []byte) ([]byte, error) {
		var state State
		if err := canonical(current, hardStateLimit, &state); err != nil {
			return nil, ErrState
		}
		if state.Version != Version || state.Mode != Mode || state.ChainID != p.ChainID ||
			state.CurrentRelease != p.CurrentRelease || state.StateSchema != p.StateSchema || state.CurrentAnchor != p.CurrentAnchor {
			return nil, ErrState
		}
		if state.Pending != nil {
			return nil, ErrPending
		}
		a, err := validateArtifact(exactArtifact, p)
		if err != nil {
			return nil, err
		}
		state.Pending = &Receipt{Sequence: e.Sequence, AdmittedHeight: p.FinalizedHeight,
			ArtifactDigest: hex.EncodeToString(p.ApprovedArtifactDigest[:]), Intent: a}
		result, err := json.Marshal(state)
		if err != nil || len(result) > hardStateLimit {
			return nil, ErrState
		}
		return result, nil
	})
}
