// Code generated by metricsgen. Disabled metrics retained unchanged.
// Optional Prometheus constructors are in metrics_prometheus.gen.go.

package state

import (
	"github.com/go-kit/kit/metrics/discard"
)

func NopMetrics() *Metrics {
	return &Metrics{
		BlockProcessingTime:   discard.NewHistogram(),
		ConsensusParamUpdates: discard.NewCounter(),
		ValidatorSetUpdates:   discard.NewCounter(),
	}
}
