// Code generated by metricsgen. Disabled metrics retained unchanged.
// Optional Prometheus constructors are in metrics_prometheus.gen.go.

package consensus

import (
	"github.com/go-kit/kit/metrics/discard"
)

func NopMetrics() *Metrics {
	return &Metrics{
		Height:                      discard.NewGauge(),
		ValidatorLastSignedHeight:   discard.NewGauge(),
		Rounds:                      discard.NewGauge(),
		RoundDurationSeconds:        discard.NewHistogram(),
		Validators:                  discard.NewGauge(),
		ValidatorsPower:             discard.NewGauge(),
		ValidatorPower:              discard.NewGauge(),
		ValidatorMissedBlocks:       discard.NewGauge(),
		MissingValidators:           discard.NewGauge(),
		MissingValidatorsPower:      discard.NewGauge(),
		ByzantineValidators:         discard.NewGauge(),
		ByzantineValidatorsPower:    discard.NewGauge(),
		BlockIntervalSeconds:        discard.NewHistogram(),
		NumTxs:                      discard.NewGauge(),
		BlockSizeBytes:              discard.NewGauge(),
		ChainSizeBytes:              discard.NewCounter(),
		TotalTxs:                    discard.NewGauge(),
		CommittedHeight:             discard.NewGauge(),
		BlockParts:                  discard.NewCounter(),
		DuplicateBlockPart:          discard.NewCounter(),
		DuplicateVote:               discard.NewCounter(),
		StepDurationSeconds:         discard.NewHistogram(),
		BlockGossipPartsReceived:    discard.NewCounter(),
		QuorumPrevoteDelay:          discard.NewGauge(),
		QuorumPrecommitDelay:        discard.NewGauge(),
		FullPrevoteDelay:            discard.NewGauge(),
		PrecommitsCounted:           discard.NewGauge(),
		PrecommitsStakingPercentage: discard.NewGauge(),
		VoteExtensionReceiveCount:   discard.NewCounter(),
		ProposalReceiveCount:        discard.NewCounter(),
		ProposalCreateCount:         discard.NewCounter(),
		RoundVotingPowerPercent:     discard.NewGauge(),
		LateVotes:                   discard.NewCounter(),
		PeerHeight:                  discard.NewGauge(),
		RoundIncrementTotal:         discard.NewCounter(),
	}
}
