// Code generated by metricsgen. Disabled metrics retained unchanged.
// Optional Prometheus constructors are in metrics_prometheus.gen.go.

package blocksync

import (
	"github.com/go-kit/kit/metrics/discard"
)

func NopMetrics() *Metrics {
	return &Metrics{
		Syncing:               discard.NewGauge(),
		NumTxs:                discard.NewGauge(),
		TotalTxs:              discard.NewGauge(),
		BlockSizeBytes:        discard.NewGauge(),
		LatestBlockHeight:     discard.NewGauge(),
		AlreadyIncludedBlocks: discard.NewCounter(),
		IngestedBlocks:        discard.NewCounter(),
		IngestedBlockDuration: discard.NewHistogram(),
	}
}
