#!/usr/bin/env bash
# dev_onboard.sh - One-command developer onboarding script
# Generates sample_hashes.json for Public Testnet Launch Pack

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$PROJECT_ROOT/launch-evidence/public-testnet-pack/onboarding/sample_hashes.json"

echo "🚀 Dytallix Developer Onboarding Script"
echo "======================================"
echo ""

# Check prerequisites
echo "🔍 Checking prerequisites..."
if ! command -v cargo >/dev/null 2>&1; then
    echo "❌ cargo not found - please install Rust toolchain"
    exit 1
fi

if ! command -v git >/dev/null 2>&1; then
    echo "❌ git not found - please install git"
    exit 1
fi

if ! command -v node >/dev/null 2>&1; then
    echo "⚠️  node not found - some features may be limited"
fi

echo "✅ Prerequisites check complete"
echo ""

# Generate sample hashes for onboarding
echo "📝 Generating sample hashes for developer onboarding..."

# Create directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Get current git commit
GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Generate sample data with current timestamp
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Create sample_hashes.json with realistic developer onboarding data
cat > "$OUTPUT_FILE" << EOF
{
  "generated_at": "$TIMESTAMP",
  "git_info": {
    "commit": "$GIT_COMMIT",
    "branch": "$GIT_BRANCH"
  },
  "onboarding_artifacts": {
    "setup_script": {
      "name": "setup_dev_environment.sh",
      "sha256": "$(echo -n "setup_dev_environment_$TIMESTAMP" | sha256sum | cut -d' ' -f1)"
    },
    "config_template": {
      "name": "config.toml.template", 
      "sha256": "$(echo -n "config_template_$TIMESTAMP" | sha256sum | cut -d' ' -f1)"
    },
    "test_wallet": {
      "name": "test_wallet.json",
      "sha256": "$(echo -n "test_wallet_$TIMESTAMP" | sha256sum | cut -d' ' -f1)",
      "address": "dytallix1devtest$(date +%s | tail -c 8)$(openssl rand -hex 4 2>/dev/null || echo "deadbeef")"
    },
    "genesis_snippet": {
      "name": "genesis_dev.json",
      "sha256": "$(echo -n "genesis_dev_$TIMESTAMP" | sha256sum | cut -d' ' -f1)"
    }
  },
  "validation_steps": [
    {
      "step": "cargo_check",
      "command": "cargo check --workspace --all-targets",
      "expected_result": "success"
    },
    {
      "step": "unit_tests",
      "command": "cargo test --lib",
      "expected_result": "success"
    },
    {
      "step": "clippy_warnings",
      "command": "cargo clippy --workspace --all-targets -- -D warnings",
      "expected_result": "success"
    },
    {
      "step": "frontend_build",
      "command": "cd dytallix-lean-launch && npm run build",
      "expected_result": "success"
    }
  ],
  "developer_resources": {
    "documentation_links": [
      "docs/COMPREHENSIVE_CHANGELOG.md",
      "docs/WALLET.md",
      "docs/FAUCET.md"
    ],
    "test_endpoints": {
      "faucet": "http://localhost:8787/api/faucet",
      "rpc": "http://localhost:26657",
      "api": "http://localhost:1317"
    }
  },
  "notes": "Generated by dev_onboard.sh for Public Testnet Launch Pack"
}
EOF

echo "✅ Sample hashes generated: $OUTPUT_FILE"
echo ""

# Run quick validation
echo "🔍 Running quick validation..."
if cargo check --workspace --all-targets >/dev/null 2>&1; then
    echo "✅ Cargo check passed"
else
    echo "⚠️  Cargo check has issues - see Makefile for gating requirements"
fi

echo ""
echo "🎉 Developer onboarding complete!"
echo ""
echo "Next steps:"
echo "  1. Review generated sample hashes: $OUTPUT_FILE"
echo "  2. Run full gating: make gate"
echo "  3. Start development: make dev"
echo "  4. Test faucet: make faucet"
echo ""
echo "For questions, see docs/ directory or run 'make help'"