// Code generated by metricsgen. Disabled metrics retained unchanged.
// Optional Prometheus constructors are in metrics_prometheus.gen.go.

package p2p

import (
	"github.com/go-kit/kit/metrics/discard"
)

func NopMetrics() *Metrics {
	return &Metrics{
		Peers:                          discard.NewGauge(),
		PeerReceiveBytesTotal:          discard.NewCounter(),
		PeerSendBytesTotal:             discard.NewCounter(),
		PeerSendQueueSize:              discard.NewGauge(),
		NumTxs:                         discard.NewGauge(),
		MessageReceiveBytesTotal:       discard.NewCounter(),
		MessageSendBytesTotal:          discard.NewCounter(),
		MessagesReceived:               discard.NewCounter(),
		MessagesReactorInFlight:        discard.NewGauge(),
		MessagesReactorPendingDuration: discard.NewHistogram(),
		MessageReactorReceiveDuration:  discard.NewHistogram(),
		MessageReactorQueueConcurrency: discard.NewGauge(),
	}
}
