// Code generated by metricsgen. Disabled metrics retained unchanged.
// Optional Prometheus constructors are in metrics_prometheus.gen.go.

package mempool

import (
	"github.com/go-kit/kit/metrics/discard"
)

func NopMetrics() *Metrics {
	return &Metrics{
		Size:                      discard.NewGauge(),
		SizeBytes:                 discard.NewGauge(),
		TxSizeBytes:               discard.NewHistogram(),
		FailedTxs:                 discard.NewCounter(),
		RejectedTxs:               discard.NewCounter(),
		EvictedTxs:                discard.NewCounter(),
		RecheckTimes:              discard.NewCounter(),
		ActiveOutboundConnections: discard.NewGauge(),
		AlreadyReceivedTxs:        discard.NewCounter(),
		BatchSize:                 discard.NewHistogram(),
		ReapedTxs:                 discard.NewCounter(),
	}
}
